<p style="text-align: center;">
    <a href="http://www.ittoluca.edu.mx" target="_blank">
        <img src="./figures/escudoITTol.png" width="100" style="float: right;" />
    </a>
</p>

<center>
    <h1>Instituto Tecnol√≥gico de Toluca</h1>
    <h2>Departamento de Sistemas y Computaci√≥n</h2>
</center>



<p><strong>Jair Gardu√±o Rodr√≠guez</strong></p>

<p><em>l21281153@toluca.tecnm.mx</em></p>

<p>No. Control: 21281153</p>

# Base de Datos "Students"
## Contenido
<div class = "alert alert-block altert-info" style="margin-top:10px">
    <ul>
    <li><a href="#descripcion">Descripci√≥n de la base de datos</a></li>
    <li><a href="#importacion">Importaci√≥n de los datos CSV a una base de datos SQLite</a></li>
    <li><a href="#consultas">Realizar consultas sobre la informaci√≥n de la base de datos</a></li>
    <li><a href="#normalizacion">Proceso de normalizaci√≥n de la base de datos</a></li>
    <li><a href = "#base_n">Consultas a base normalizada</a></li>
    </ul>
</div>

<a id = "descripcion"></a>
# Descripci√≥n de la Base de Datos  

El archivo csv  **"Students"** almacena informaci√≥n sobre los estudiantes, incluyendo su identificaci√≥n, datos personales, acad√©micos y de contacto. Su prop√≥sito principal es facilitar la gesti√≥n y el an√°lisis de los datos estudiantiles dentro de una instituci√≥n educativa.  

Esta estructura permite registrar informaci√≥n clave sobre cada estudiante, lo que facilita la administraci√≥n acad√©mica y el seguimiento del rendimiento de los alumnos a lo largo de su formaci√≥n.  

---

## üìÇ **Estructura de los datos**  

Los siguientes datos fueron obtenidos a partir de una consulta realizada con **pandas**, cuyo c√≥digo se encuentra m√°s adelante.  

| **Nombre del Campo**  | **Tipo de Dato** | **Descripci√≥n** |
|--------------------|------------|-------------|
| **StudentID**      | `int64`     | Identificador √∫nico del estudiante (**Clave primaria**). Se utiliza para diferenciar a cada alumno en la base de datos. |
| **Name**          | `object`    | Nombre completo del estudiante, facilitando su identificaci√≥n dentro del sistema. |
| **Age**           | `int64`     | Edad del estudiante en formato num√©rico, √∫til para an√°lisis demogr√°ficos y segmentaci√≥n. |
| **Email**         | `object`    | Direcci√≥n de correo electr√≥nico del estudiante, permitiendo la comunicaci√≥n institucional. |
| **Department**    | `object`    | Departamento acad√©mico al que pertenece el estudiante (Ejemplo: Ingenier√≠a, Ciencias, Humanidades, etc.). |
| **GPA**          | `float64`   | Promedio general de calificaciones del estudiante (**Grade Point Average**), una m√©trica clave para evaluar su desempe√±o acad√©mico. |
| **GraduationYear** | `int64`     | A√±o esperado de graduaci√≥n del estudiante, facilitando la planificaci√≥n de egresos y ceremonias de graduaci√≥n. |

---

## üéØ **Objetivos de los datos**  

La tabla **"Students"** permite gestionar eficientemente la informaci√≥n de los estudiantes dentro de un sistema acad√©mico. Sus objetivos principales incluyen:  

- **Facilitar la identificaci√≥n y administraci√≥n de los estudiantes**, asegurando un acceso r√°pido y estructurado a sus datos personales y acad√©micos.  
- **Optimizar la comunicaci√≥n institucional** mediante el almacenamiento de correos electr√≥nicos de los alumnos.  
- **Registrar el desempe√±o acad√©mico** de los estudiantes mediante el GPA, permitiendo evaluaciones y reportes sobre su progreso.  
- **Ayudar en la planificaci√≥n de graduaciones** y otras actividades administrativas al almacenar el a√±o de egreso estimado.  

---

## üìä **Aplicaciones de los datos**  

La informaci√≥n contenida en esta tabla puede ser utilizada como base para diversos sistemas y an√°lisis dentro de una instituci√≥n educativa, tales como:  

- **üìö Sistemas de gesti√≥n estudiantil**  
  - Permite registrar, actualizar y consultar los datos de los estudiantes de manera eficiente.  
  - Facilita la integraci√≥n con otros m√≥dulos acad√©micos como calificaciones, asistencia y matr√≠culas.  

- **üìà An√°lisis de desempe√±o acad√©mico**  
  - Permite evaluar tendencias en el rendimiento estudiantil a trav√©s del GPA.  
  - Facilita la identificaci√≥n de alumnos en riesgo acad√©mico o con excelencia acad√©mica.  

- **üì° Plataformas de comunicaci√≥n universitaria**  
  - Permite el env√≠o automatizado de informaci√≥n institucional a los correos electr√≥nicos de los alumnos.  
  - Facilita la segmentaci√≥n de estudiantes seg√∫n departamento o a√±o de graduaci√≥n.  

- **üñ•Ô∏è Integraci√≥n con otros sistemas administrativos**  
  - Puede enlazarse con m√≥dulos de inscripciones, gesti√≥n de cursos y generaci√≥n de reportes.  
  - Facilita el an√°lisis de tasas de egreso y permanencia en la instituci√≥n.  

---

In [29]:
# Consulta para saber un poco de contexto de los datos
# 1. ¬øCu√°ntas columnas tiene el archivo?
# 2. ¬øCu√°ntas filas tiene el archivo?
# 3. ¬øQu√© tipo de datos tiene cada columna?
import pandas as pd
df = pd.read_csv('students.csv')
print(f"Tipos de datos del archivo: \n{df.dtypes}")
print("#"*25)
print(f"Numero de columnas: {len(df.columns)}")
print(f"Numero de filas: {len(df)}")

Tipos de datos del archivo:
StudentID           int64
Name               object
Age                 int64
Email              object
Department         object
GPA               float64
GraduationYear      int64
dtype: object
#########################
Numero de columnas: 7
Numero de filas: 200


<a id = "importacion"> </a>
## Importaci√≥n de los datos CSV a una base de datos SQLite



1. **Importar las librer√≠as necesarias**:
    ```python
    import pandas as pd
    import sqlite3
    ```

2. **Cargar el archivo CSV**:
    ```python
    csv_file = "students.csv"  
    df = pd.read_csv(csv_file)
    ```

3. **Conectar a la base de datos SQLite**:
    ```python
    conn = sqlite3.connect("students.db")
    cursor = conn.cursor()
    ```

4. **Generar la sentencia `CREATE TABLE` autom√°ticamente**:
    ```python
    column_types = {
         "int64": "INTEGER",
         "float64": "REAL",
         "object": "TEXT"
    }

    columns_sql = ", ".join([f"{col} {column_types[str(dtype)]}" for col, dtype in df.dtypes.items()])
    create_table_sql = f"CREATE TABLE IF NOT EXISTS Students ({columns_sql})"
    ```

5. **Ejecutar la creaci√≥n de la tabla**:
    ```python
    cursor.execute(create_table_sql)
    ```

6. **Insertar los datos en la tabla**:
    ```python
    df.to_sql("Students", conn, if_exists="append", index=False)
    ```

7. **Confirmar y cerrar conexi√≥n**:
    ```python
    conn.commit()
    conn.close()
    ```

8. **Mensaje de confirmaci√≥n**:
    ```python
    print("Base de datos creada autom√°ticamente y datos importados.")
    ```

In [2]:
import sqlite3
import pandas as pd

# 1Ô∏è‚É£ Cargar el archivo CSV
csv_file = "students.csv"
df = pd.read_csv(csv_file)

# 2Ô∏è‚É£ Conectar a la base de datos SQLite
conn = sqlite3.connect("students.db")
cursor = conn.cursor()

# 3Ô∏è‚É£ Generar la sentencia CREATE TABLE autom√°ticamente
column_types = {
    "int64": "INTEGER",
    "float64": "REAL",
    "object": "TEXT"
}

columns_sql = ", ".join([f"{col} {column_types[str(dtype)]}" for col, dtype in df.dtypes.items()])
create_table_sql = f"CREATE TABLE IF NOT EXISTS Students ({columns_sql})"

# 4Ô∏è‚É£ Ejecutar la creaci√≥n de la tabla
cursor.execute(create_table_sql)

# 5Ô∏è‚É£ Insertar los datos en la tabla
df.to_sql("Students", conn, if_exists="append", index=False)

# 6Ô∏è‚É£ Confirmar y cerrar conexi√≥n
conn.commit()
conn.close()

print("Base de datos creada autom√°ticamente y datos importados.")

Base de datos creada autom√°ticamente y datos importados.

<a id="consultas"></a>

## Consultas sobre la informaci√≥n de la base de datos

A continuaci√≥n, se presentan algunas consultas SQL para obtener informaci√≥n relevante de la base de datos **Students**.

1. **Obtener todos los estudiantes del departamento de "Physics"**:
    ```sql
    SELECT * FROM Students WHERE Department = 'Physics';
    ```

2. **Contar el n√∫mero de estudiantes en cada departamento**:
    ```sql
    SELECT Department, COUNT(*) as StudentCount FROM Students GROUP BY Department;
    ```

3. **Obtener los estudiantes con un GPA mayor a 3.5**:
    ```sql
    SELECT * FROM Students WHERE GPA > 3.5;
    ```

4. **Obtener el promedio de edad de los estudiantes en cada departamento**:
    ```sql
    SELECT Department, AVG(Age) as AverageAge FROM Students GROUP BY Department;
    ```

5. **Obtener los estudiantes que se graduar√°n en el a√±o 2025**:
    ```sql
    SELECT * FROM Students WHERE GraduationYear = 2025;
    ```

6. **Obtener el estudiante con el GPA m√°s alto**:
    ```sql
    SELECT * FROM Students ORDER BY GPA DESC LIMIT 1;
    ```

7. **Obtener el n√∫mero total de estudiantes en la base de datos**:
    ```sql
    SELECT COUNT(*) as TotalStudents FROM Students;
    ```

8. **Obtener los nombres y correos electr√≥nicos de los estudiantes ordenados por nombre**:
    ```sql
    SELECT Name, Email FROM Students ORDER BY Name;
    ```

9. **Obtener el promedio de GPA de todos los estudiantes**:
    ```sql
    SELECT AVG(GPA) as AverageGPA FROM Students;
    ```

10. **Obtener los estudiantes cuyo nombre comienza con la letra 'A'**:
    ```sql
    SELECT * FROM Students WHERE Name LIKE 'A%';
    ```

In [3]:
import pandas as pd
import sqlite3

# Conectar a la base de datos SQLite
conn = sqlite3.connect("students.db")

# 1. Obtener los primeros 2 estudiantes del departamento de "Physics"
physics_students = pd.read_sql_query("SELECT * FROM Students WHERE Department = 'Physics' LIMIT 2", conn)
print("Primeros 2 estudiantes del departamento de 'Physics':")
print(physics_students)

# 2. Contar el n√∫mero de estudiantes en cada departamento (limitar a 2 departamentos)
student_count_per_department = pd.read_sql_query("SELECT Department, COUNT(*) as StudentCount FROM Students GROUP BY Department LIMIT 2", conn)
print("\nN√∫mero de estudiantes por departamento (limitado a 2 departamentos):")
print(student_count_per_department)

# 3. Obtener los primeros 2 estudiantes con un GPA mayor a 3.5
high_gpa_students = pd.read_sql_query("SELECT * FROM Students WHERE GPA > 3.5 LIMIT 2", conn)
print("\nEstudiantes con GPA mayor a 3.5 (limitado a 2):")
print(high_gpa_students)

# 4. Obtener el promedio de edad de los estudiantes en cada departamento (limitar a 2 departamentos)
average_age_per_department = pd.read_sql_query("SELECT Department, AVG(Age) as AverageAge FROM Students GROUP BY Department LIMIT 2", conn)
print("\nPromedio de edad por departamento (limitado a 2 departamentos):")
print(average_age_per_department)

# 5. Obtener los primeros 2 estudiantes que se graduar√°n en el a√±o 2025
graduates_2025 = pd.read_sql_query("SELECT * FROM Students WHERE GraduationYear = 2025 LIMIT 2", conn)
print("\nEstudiantes que se graduar√°n en 2025 (limitado a 2):")
print(graduates_2025)

# 6. Obtener el estudiante con el GPA m√°s alto (limitado a 2, aunque solo debe haber 1)
top_gpa_student = pd.read_sql_query("SELECT * FROM Students ORDER BY GPA DESC LIMIT 2", conn)
print("\nEstudiante con el GPA m√°s alto (limitado a 2, aunque solo deber√≠a haber 1):")
print(top_gpa_student)

# 7. Obtener el n√∫mero total de estudiantes en la base de datos (limitado a 2)
total_students = pd.read_sql_query("SELECT COUNT(*) as TotalStudents FROM Students LIMIT 2", conn)
print("\nN√∫mero total de estudiantes (limitado a 2):")
print(total_students)

# 8. Obtener los primeros 2 nombres y correos electr√≥nicos de los estudiantes ordenados por nombre
names_emails_sorted = pd.read_sql_query("SELECT Name, Email FROM Students ORDER BY Name LIMIT 2", conn)
print("\nNombres y correos electr√≥nicos de los primeros 2 estudiantes ordenados por nombre:")
print(names_emails_sorted)

# 9. Obtener el promedio de GPA de todos los estudiantes (limitado a 2)
average_gpa = pd.read_sql_query("SELECT AVG(GPA) as AverageGPA FROM Students LIMIT 2", conn)
print("\nPromedio de GPA de todos los estudiantes (limitado a 2):")
print(average_gpa)

# 10. Obtener los primeros 2 estudiantes cuyo nombre comienza con la letra 'A'
students_name_starts_with_a = pd.read_sql_query("SELECT * FROM Students WHERE Name LIKE 'A%' LIMIT 2", conn)
print("\nEstudiantes cuyo nombre comienza con la letra 'A' (limitado a 2):")
print(students_name_starts_with_a)

# Cerrar la conexi√≥n
conn.close()

Primeros 2 estudiantes del departamento de 'Physics':
   StudentID               Name  Age                          Email  \
0       1396  Jonathan Gonzalez   22           hollydavis@gmail.com
1       6716     Kenneth Morrow   24  ganderson@wheeler-atkins.info

  Department   GPA  GraduationYear
0    Physics  2.95            2027
1    Physics  3.55            2029

N√∫mero de estudiantes por departamento (limitado a 2 departamentos):
  Department  StudentCount
0    Biology            27
1  Chemistry            46

Estudiantes con GPA mayor a 3.5 (limitado a 2):
   StudentID            Name  Age                          Email Department  \
0       8774    Andrew Roach   23             vbecker@harvey.com  Chemistry
1       6716  Kenneth Morrow   24  ganderson@wheeler-atkins.info    Physics

    GPA  GraduationYear
0  3.75            2027
1  3.55            2029

Promedio de edad por departamento (limitado a 2 departamentos):
  Department  AverageAge
0    Biology   21.185185
1  Chemistry   21.521739

Estudiantes que se graduar√°n en 2025 (limitado a 2):
   StudentID              Name  Age                           Email  \
0       8830  Kaitlyn Martinez   18            hayesdiane@gmail.com
1       5986  Samantha Sellers   20  michelle27@hubbard-webster.com

    Department   GPA  GraduationYear
0    Chemistry  2.29            2025
1  Mathematics  3.44            2025

Estudiante con el GPA m√°s alto (limitado a 2, aunque solo deber√≠a haber 1):
   StudentID          Name  Age                 Email   Department   GPA  \
0       7637     Peter Day   19     smaynard@cole.com  Mathematics  3.99
1       7265  Kevin Bowman   25  brownronald@clay.com    Chemistry  3.98

   GraduationYear
0            2029
1            2030

N√∫mero total de estudiantes (limitado a 2):
   TotalStudents
0            200

Nombres y correos electr√≥nicos de los primeros 2 estudiantes ordenados por nombre:
                 Name                         Email
0          Adam Evans  bryantmargaret@hernandez.com
1  Alejandra Galloway      danielpowers@schmidt.com

Promedio de GPA de todos los estudiantes (limitado a 2):
   AverageGPA
0     3.02785

Estudiantes cuyo nombre comienza con la letra 'A' (limitado a 2):
   StudentID          Name  Age                         Email Department  \
0       8774  Andrew Roach   23            vbecker@harvey.com  Chemistry
1       3254    Adam Evans   20  bryantmargaret@hernandez.com    Physics

    GPA  GraduationYear
0  3.75            2027
1  3.42            2026

<a id = "normalizacion"></a>
# Proceso de normalizaci√≥n de la base de datos
En el proceso de normalizaci√≥n de una base de datos, se busca organizar los datos de manera que se eliminen redundancias y dependencias innecesarias, dividiendo las tablas en estructuras m√°s peque√±as y f√°ciles de mantener. Este proceso se realiza en varias formas normales, siendo las tres primeras las m√°s comunes. A continuaci√≥n, te explico brevemente cada una:

### 1. Primera Forma Normal (1FN)
Una tabla est√° en **Primera Forma Normal** si:
- Todos los valores son at√≥micos (es decir, no hay grupos repetitivos de columnas o valores m√∫ltiples en una misma celda).
- Cada columna contiene un √∫nico valor.
- Cada fila es √∫nica.

### 2. Segunda Forma Normal (2FN)
Una tabla est√° en **Segunda Forma Normal** si:
- Cumple con la Primera Forma Normal.
- Todas las columnas no clave dependen completamente de la clave primaria, es decir, no debe haber dependencias parciales.

### 3. Tercera Forma Normal (3FN)
Una tabla est√° en **Tercera Forma Normal** si:
- Cumple con la Segunda Forma Normal.
- No existen dependencias transitivas, es decir, las columnas no clave no deben depender de otras columnas no clave.

---

## An√°lisis de la Tabla `Students`

Analizando la tabla `Students` que contiene informaci√≥n sobre los estudiantes, como su nombre, departamento, GPA, edad y a√±o de graduaci√≥n, podemos verificar en qu√© forma normal se encuentra:

<div style="text-align: center;">
    <img src="./figures/First_table.png" width="20%" alt="Tabla de estudiantes antes de la normalizaci√≥n" />
</div>

### 1. Cumple con la Primera Forma Normal (1FN)
La tabla **cumple con la Primera Forma Normal** porque:
- Todos los valores en las celdas son at√≥micos.
- No existen columnas con m√°s de un valor (como una lista de valores).
- Cada fila es √∫nica.

### 2. Cumple con la Segunda Forma Normal (2FN)
La tabla **cumple con la Segunda Forma Normal** porque:
- Todas las columnas no clave dependen completamente de la clave primaria. 
- En este caso, la clave primaria es el `StudentID` y todos los atributos (como el nombre, GPA, edad y departamento) dependen directamente de este ID. No existen dependencias parciales.

### 3. No cumple con la Tercera Forma Normal (3FN)
La tabla **no cumple con la Tercera Forma Normal** debido a:
- La columna `DepartmentID` depende de otra columna no clave.
- Esto genera una dependencia transitiva, ya que `DepartmentID` puede estar asociado con informaci√≥n adicional del departamento (como su nombre), pero esta informaci√≥n se encuentra en la misma tabla, lo que genera redundancia y hace que no se cumpla con la 3FN.

---
## Propuesta de Modificaci√≥n para Cumplir con la Tercera Forma Normal (3FN)

Tras analizar la tabla `Students`, se ha encontrado que no cumple con la **Tercera Forma Normal (3FN)** debido a las dependencias transitivas, en las cuales el `DepartmentID` depende de una columna no clave.

### Soluci√≥n Propuesta

Para cumplir con la **Tercera Forma Normal**, proponemos los siguientes cambios:

1. **Crear una nueva tabla llamada `Departments`**:
   - Esta tabla almacenar√° la informaci√≥n relacionada con los departamentos, como el `DepartmentID` (clave primaria) y el `Name` del departamento.

2. **Modificar la tabla `Students`**:
   - Se a√±adir√° una columna `DepartmentID` que actuar√° como clave for√°nea (FK) para referenciar la tabla `Departments`.
   - De esta manera, eliminamos la dependencia transitiva, ya que la informaci√≥n del departamento se gestionar√° en una tabla separada.

### Nueva Estructura de las Tablas

<div style="text-align: center;">
    <img src="./figures/normalize_table.png" width="30%" alt="Tabla de estudiantes antes de la normalizaci√≥n" />
</div>

### Explicaci√≥n del Cambio

- **Tabla `Departments`**: Almacena la informaci√≥n √∫nica del departamento, de forma que si m√°s estudiantes pertenecen al mismo departamento, no se repita la informaci√≥n del departamento en cada fila de la tabla `Students`. Esto elimina redundancias.
  
- **Tabla `Students`**: Ahora la columna `DepartmentID` se convierte en una clave for√°nea que apunta a la tabla `Departments`. De esta forma, evitamos la dependencia transitiva entre el nombre del departamento y el resto de los atributos de los estudiantes.

Este cambio asegura que la base de datos cumpla con la **Tercera Forma Normal (3FN)** y sea m√°s eficiente en t√©rminos de almacenamiento y mantenimiento.

In [4]:
import pandas as pd
import sqlite3

# Conectar a la base de datos SQLite
conn = sqlite3.connect("students.db")

# 1. Obtener los departamentos distintos de la tabla Students
departments = pd.read_sql_query("SELECT DISTINCT(Department) FROM Students", conn)

# 2. Crear un DataFrame con los departamentos y asignarles un ID
departments['DepartmentID'] = range(1, len(departments) + 1)

# 3. Mostrar los departamentos con su nuevo ID
print("Departamentos con ID:")
print(departments)

# 4. Crear la tabla Departments con el ID y el nombre del departamento
conn.execute("""
    CREATE TABLE IF NOT EXISTS Departments (
        DepartmentID INTEGER PRIMARY KEY,
        DepartmentName TEXT
    )
""")

# 5. Insertar los departamentos en la tabla Departments
for _, row in departments.iterrows():
    conn.execute("INSERT INTO Departments (DepartmentID, DepartmentName) VALUES (?, ?)", 
                 (row['DepartmentID'], row['Department']))

# 6. Modificar la tabla Students para agregar el campo DepartmentID (FK)
conn.execute("""
    ALTER TABLE Students 
    ADD COLUMN DepartmentID INTEGER
""")

# 7. Actualizar la tabla Students para que tenga el DepartmentID correcto
for _, row in departments.iterrows():
    conn.execute("""
        UPDATE Students 
        SET DepartmentID = ?
        WHERE Department = ?
    """, (row['DepartmentID'], row['Department']))

# Commit para guardar cambios
conn.commit()

# 8. Verificaci√≥n: Mostrar la tabla Departments
print("Tabla Departments:")
departments_from_db = pd.read_sql_query("SELECT * FROM Departments", conn)
print(departments_from_db)

# Cerrar la conexi√≥n
conn.close()

Departamentos con ID:
         Department  DepartmentID
0       Mathematics             1
1         Chemistry             2
2           Physics             3
3  Computer Science             4
4           Biology             5
Tabla Departments:
   DepartmentID    DepartmentName
0             1       Mathematics
1             2         Chemistry
2             3           Physics
3             4  Computer Science
4             5           Biology

In [5]:
import pandas as pd
import sqlite3

# Conectar a la base de datos SQLite
conn = sqlite3.connect("students.db")

# 1. Crear una nueva tabla sin la columna Department
conn.execute("""
    CREATE TABLE Students_temp AS
    SELECT StudentID, Name, Age, GPA, GraduationYear, DepartmentID
    FROM Students
""")

# 2. Eliminar la tabla original y renombrar la nueva
conn.execute("DROP TABLE Students")
conn.execute("ALTER TABLE Students_temp RENAME TO Students")

# 3. Verificar la estructura final
departments_from_db = pd.read_sql_query("SELECT * FROM Departments", conn)
students_from_db = pd.read_sql_query("SELECT * FROM Students", conn)

print("Tabla Departments:")
print(departments_from_db)

print("\nTabla Students con solo DepartmentID:")
print(students_from_db)

# Guardar cambios y cerrar conexi√≥n
conn.commit()
conn.close()

Tabla Departments:
   DepartmentID    DepartmentName
0             1       Mathematics
1             2         Chemistry
2             3           Physics
3             4  Computer Science
4             5           Biology

Tabla Students con solo DepartmentID:
     StudentID                 Name  Age   GPA  GraduationYear  DepartmentID
0         3336         David Palmer   19  3.16            2026             1
1         8774         Andrew Roach   23  3.75            2027             2
2         1396    Jonathan Gonzalez   22  2.95            2027             3
3         6716       Kenneth Morrow   24  3.55            2029             3
4         8830     Kaitlyn Martinez   18  2.29            2025             2
..         ...                  ...  ...   ...             ...           ...
195       3274  Catherine Velasquez   22  2.71            2025             3
196       3609         Joyce Thomas   19  2.22            2030             2
197       9179       Theresa Hughes   21  3.23            2025             1
198       4463        Steven Golden   19  3.90            2025             4
199       6178     Miss April Smith   20  3.15            2028             1

[200 rows x 6 columns]

# Consultas a base normalizada
#### Explicaci√≥n de las Consultas sobre la Informaci√≥n de la Base de Datos

En esta secci√≥n, se realizaron varias consultas SQL para obtener informaci√≥n relevante de la base de datos **Students**. A continuaci√≥n, se explica cada una de las consultas realizadas:

1. **Obtener todos los estudiantes junto con el nombre de su departamento**:
    ```sql
    SELECT s.StudentID, s.Name, s.Age, s.GPA, s.GraduationYear, d.DepartmentName
    FROM Students s
    JOIN Departments d ON s.DepartmentID = d.DepartmentID LIMIT 2;
    ```
    Esta consulta utiliza una uni√≥n (`JOIN`) entre las tablas `Students` y `Departments` para obtener informaci√≥n completa de los estudiantes, incluyendo el nombre de su departamento. Se limita a mostrar solo los primeros 2 resultados.
<a id = "base_n"></a>

2. **Contar el n√∫mero de estudiantes en cada departamento**:
    ```sql
    SELECT d.DepartmentName, COUNT(*) as StudentCount
    FROM Students s
    JOIN Departments d ON s.DepartmentID = d.DepartmentID
    GROUP BY d.DepartmentName LIMIT 2;
    ```
    Esta consulta cuenta el n√∫mero de estudiantes en cada departamento. Utiliza una uni√≥n (`JOIN`) entre las tablas `Students` y `Departments` y agrupa los resultados por el nombre del departamento (`GROUP BY`). Se limita a mostrar solo los primeros 2 resultados.

3. **Obtener el promedio de edad de los estudiantes en cada departamento**:
    ```sql
    SELECT d.DepartmentName, AVG(s.Age) as AverageAge
    FROM Students s
    JOIN Departments d ON s.DepartmentID = d.DepartmentID
    GROUP BY d.DepartmentName LIMIT 2;
    ```
    Esta consulta calcula el promedio de edad de los estudiantes en cada departamento. Utiliza una uni√≥n (`JOIN`) entre las tablas `Students` y `Departments` y agrupa los resultados por el nombre del departamento (`GROUP BY`). Se limita a mostrar solo los primeros 2 resultados.

Estas consultas permiten obtener informaci√≥n detallada y resumida sobre los estudiantes y sus departamentos, facilitando el an√°lisis y la toma de decisiones dentro de la instituci√≥n educativa.

In [14]:
import pandas as pd
import sqlite3

# Conectar a la base de datos SQLite
conn = sqlite3.connect("students.db")

# 1. Obtener todos los estudiantes junto con el nombre de su departamento
students_with_departments = pd.read_sql_query("""
    SELECT s.StudentID, s.Name, s.Age, s.GPA, s.GraduationYear, d.DepartmentName
    FROM Students s
    JOIN Departments d ON s.DepartmentID = d.DepartmentID LIMIT 2
""", conn)
print("Estudiantes con el nombre de su departamento:")
print(students_with_departments)

# 2. Contar el n√∫mero de estudiantes en cada departamento
student_count_per_department = pd.read_sql_query("""
    SELECT d.DepartmentName, COUNT(*) as StudentCount
    FROM Students s
    JOIN Departments d ON s.DepartmentID = d.DepartmentID
    GROUP BY d.DepartmentName LIMIT 2
""", conn)
print("\nN√∫mero de estudiantes por departamento:")
print(student_count_per_department)



# 3. Obtener el promedio de edad de los estudiantes en cada departamento
average_age_per_department = pd.read_sql_query("""
    SELECT d.DepartmentName, AVG(s.Age) as AverageAge
    FROM Students s
    JOIN Departments d ON s.DepartmentID = d.DepartmentID
    GROUP BY d.DepartmentName
    LIMIT 2
""", conn)
print("\nPromedio de edad por departamento:")
print(average_age_per_department)

# Cerrar la conexi√≥n
conn.close()

Estudiantes con el nombre de su departamento:
   StudentID          Name  Age   GPA  GraduationYear DepartmentName
0       3336  David Palmer   19  3.16            2026    Mathematics
1       8774  Andrew Roach   23  3.75            2027      Chemistry

N√∫mero de estudiantes por departamento:
  DepartmentName  StudentCount
0        Biology            27
1      Chemistry            46

Promedio de edad por departamento:
  DepartmentName  AverageAge
0        Biology   21.185185
1      Chemistry   21.521739